### ISSUE TITLE
UIImagePickerのREADMEを追加する

### ISSUE THREAD

**Issue by MasakazOzaki** [lifeistech/toybox#125]

**Comment by risako070310** [comment]
@MasakazOzaki (cc @kyoya1123 )
Readmeを書くために色々調べていて、iOS14以降ではUIImagePickerControllerの`sourceType = .photoLibrary`は非推奨でPHPickerViewControllerという新たなピッカーがあると知って、UIImagePickerはカメラのみのtoyにしてPHPicker x PhotoKitのtoyを別にした方がいいのかなとか思ったのですがいかがでしょうか
